In [13]:
import torch

In [16]:
t = torch.tensor([1, 1, 1])
print(t)
print(t.shape)

tensor([1, 1, 1])
torch.Size([3])


In [17]:
print(t.unsqueeze(dim=0))
print(t.unsqueeze(dim=0).shape)

tensor([[1, 1, 1]])
torch.Size([1, 3])


In [18]:
print(t.unsqueeze(dim=1))
print(t.unsqueeze(dim=1).shape)

tensor([[1],
        [1],
        [1]])
torch.Size([3, 1])


In [19]:
t1 = torch.tensor([1, 1, 1])
t2 = torch.tensor([2, 2, 2])
t3 = torch.tensor([3, 3, 3])

In [20]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([3])
torch.Size([3])
torch.Size([3])


In [21]:
torch.cat(
    (t1, t2, t3),
    dim=0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
torch.stack(
    (t1, t2, t3),
    dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [28]:
torch.stack(
    (t1, t2, t3),
    dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [24]:
t1.unsqueeze(0)

tensor([[1, 1, 1]])

In [25]:
torch.cat(
    (
        t1.unsqueeze(0),
        t2.unsqueeze(0),
        t3.unsqueeze(0),
    ),
    dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [33]:
t1

tensor([1, 1, 1])

In [34]:
t1.shape

torch.Size([3])

In [35]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [36]:
t1.unsqueeze(dim=0).shape

torch.Size([1, 3])

In [37]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [38]:
t1.unsqueeze(dim=1).shape

torch.Size([3, 1])